# @package _global_

defaults:
  - /config
  - /model@trainable.model: cnn
  - /datamodule: artifact
  - /trainer: default
  - /infrastructure: local
  - /checkpoint: default
  - _self_

metadata:
  name: default
  description: scaffold experiment
  tags: [scaffold]

trainable:
  preprocessor: null
  postprocessor: null
