tracking_uri: ${oc.env:AIDE_TRACKING_URI,sqlite:///${oc.env:AIDE_PROJECT_ROOT}/workspace/metadata/mlflow.db}
artifact_location: ${oc.env:AIDE_ARTIFACT_LOCATION,${oc.env:AIDE_PROJECT_ROOT}/workspace/artifacts}
save_dir: ${oc.env:AIDE_SAVE_DIR,${oc.env:AIDE_PROJECT_ROOT}/workspace/lightning_logs}