# @package _global_

defaults:
  - /config
  - /model: cnn
  - /datamodule: default
  - /trainer: default
  - /infrastructure: local
  - /checkpoint: default
  - _self_

metadata:
  name: default
  description: scaffold experiment
  tags: [scaffold]
