artifact_uri: ${oc.env:AIDE_DATASET_MANIFEST}
transforms:
  - class_name: scaffold_normalize
    params:
      apply_to: [all]
  - class_name: scaffold_random_crop
    params:
      size: 32
      padding: 4
      apply_to: [train]
batch_size: 32
pin_memory: false
num_workers: 8
persistent_workers: true
